bas/models/Category.php
<?php


namespace app\models;

use yii\db\ActiveRecord;

class Category extends ActiveRecord
{
    public static function tableName() {
        return 'category';
    }

    public function getCategories() {
        return Category::find()->asArray()->all();
    }
}

bas/controllers/CategoryController.php
<?php


namespace app\controllers;

use app\models\Good;
use yii\web\Controller;
use Yii;

class CategoryController extends Controller
{
    public function actionIndex(){
        $goods = new Good();
        $goods = $goods->getAllGoods();
        return $this->render('index', compact('goods'));
    }

    public function actionView($id){
        $catGoods = new Good();
        $catGoods = $catGoods->getGoodsCategories($id);
        return $this->render('view', compact('catGoods'));
    }

    public function actionSearch() {
        $search = strip_tags(Yii::$app->request->get('search'));
        $goods = new Good();
        $goods = $goods->getSearchGoodsResults($search);
        return $this->render('search', compact('goods','search'));
    }
}

bas/controllers/GoodController.php
<?php


namespace app\controllers;
use yii\web\Controller;
use app\models\Good;

class GoodController extends Controller
{
    public function actionIndex($name) {
        $good = new Good();
        $good = $good->getOneGood($name);
        return $this->render('index', compact('good'));
    }
}

bas/views/category/index.php
<?=\app\widgets\MenuWidgets::widget();?>
<?php use yii\helpers\Url;?>

<div class="container">
    <div class="row">

    <?php foreach ($goods as $good):?>
        <div class="col-4">
            <div class="product">
                <div class="product-img">
                    <img src="../web/img/<?= $good['img'] ?>" alt="<?= $good['name'] ?>">
                </div>
                <div class="product-name"><?= $good['name'] ?></div>
                <div class="product-descr"><?= $good['composition'] ?></div>
                <div class="product-price">Цена: <?= $good['price'] ?> рублей</div>
                <div class="product-buttons">
                    <a href="#" data-name="<?=$good['link_name']?>" type="button" class="product-button__add btn btn-success">Заказать</a>
                    <a href="<?= Url::to(['good/index', 'name'=>$good['link_name']])?>" type="button" class="product-button__more btn btn-primary">Подробнее</a>
                </div>
            </div>
        </div>
        <?php endforeach;?>
    </div>
</div>

bas/views/category/search.php
<?php use yii\helpers\Url;?>
<div class="container">

    <h2 style="text-align: center" ">Результаты поиска по запросу: <?=$search?></h2>
    <div class="row justify-content-center">
    <?php if ($goods):
        foreach ($goods as $good):?>
            <div class="col-4">
                <div class="product">
                    <div class="product-img">
                        <img src="../web/img/<?= $good['img'] ?>" alt="<?= $good['name'] ?>">
                    </div>
                    <div class="product-name"><?= $good['name'] ?></div>
                    <div class="product-descr"><?= $good['composition'] ?></div>
                    <div class="product-price">Цена: <?= $good['price'] ?> рублей</div>
                    <div class="product-buttons">
                        <a href="#" data-name="<?=$good['link_name']?>" type="button" class="product-button__add btn btn-success">Заказать</a>
                        <a href="<?= Url::to(['good/index', 'name'=>$good['link_name']])?>" type="button" class="product-button__more btn btn-primary">Подробнее</a>
                    </div>
                </div>
            </div>
        <?php
        endforeach;
        else:?>
        <h4>Ничего не найдено</h4>
        <?php endif;?>
    </div>
</div>

bas/views/category/view.php
<?php echo \app\widgets\MenuWidgets::widget();
use yii\helpers\Url;?>

<div class="container">
    <div class="row  justify-content-center">

        <?php foreach ($catGoods as $good):?>
            <div class="col-4">
                <div class="product">
                    <div class="product-img">
                        <img src="../web/img/<?= $good['img'] ?>" alt="<?= $good['name'] ?>">
                    </div>
                    <div class="product-name"><?= $good['name'] ?></div>
                    <div class="product-descr"><?= $good['composition'] ?></div>
                    <div class="product-price">Цена: <?= $good['price'] ?> рублей</div>
                    <div class="product-buttons">
                        <a href="#" data-name="<?=$good['link_name']?>" type="button" class="product-button__add btn btn-success">Заказать</a>
                        <a href="<?= Url::to(['good/index', 'name'=>$good['link_name']])?>" type="button" class="product-button__more btn btn-primary">Подробнее</a>
                    </div>
                </div>
            </div>
        <?php endforeach;?>
    </div>
</div>